name: Automated QA
on: push
jobs:
  myiam-py:
    name: myiam-py tests
    runs-on: ubuntu-latest
    services:
      ddb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    defaults:
      run:
        working-directory: myiam-py
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*') }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements/requirements.test.txt
      - name: Run Tests
        env:
          AWS_ACCESS_KEY_ID: --
          AWS_SECRET_ACCESS_KEY: --
        run: pytest
